### ISSUE TITLE
show only in cat doesnt work

### ISSUE THREAD

**Issue by SaintEcho** [Hoizame/SimpleEnergyBar#1]
with this setting set to true the bar never shows whether im in cat or not in classic wow

**Comment by kgagnon** [comment]
As I am the first to do so, I will confirm that this is indeed an issue. WoW Classic.

**Comment by Hoizame** [comment]
Hey I think the addon is maybe using the wrong shapeshift form can you please go into cat and type `/dump GetShapeshiftForm()` in chat and post me the result?

**Comment by SaintEcho** [comment]
cat is form 3 as long as you have aquatic, if you dont have aquatic its form 2.

**Comment by SaintEcho** [comment]
Also i can confirm thats the issue because the energy bar shows up in aquatic with that option enabled.

**Comment by Hoizame** [comment]
hmm that with 2 stance numbers is bad :D changed the code to check for buffname now.
Can you please test v1.0.6? Update and `/reload` ingame is enough

**Comment by rookztr** [comment]
I tried v1.0.6 but still nope, no bar. I can also confirm what Saint wrote about aquatic form, I changed the stance from 2 to 3 in the v1.0.5 and then it works just fine.

**Comment by carneiror** [comment]
I think if you try to set a `showInStealth` value it starts working. I don't know anything about lua but the `showInStealth` value but be falsy without a value.

`/seb showInStealth 1` or `/seb showInStealth 0` fixes the issue

**Comment by Hoizame** [comment]
Oh just forgot to remove a check sry updated again

**Comment by rookztr** [comment]
v1.0.7 works just fine for me, thanks!

**Comment by Hoizame** [comment]
Thanks for the reports :)
