### ISSUE TITLE
SimpleEnergyBar doesn't hide when UI is hidden.

### ISSUE THREAD

**Issue by Glitchingreality** [Hoizame/SimpleEnergyBar#5]
Hello, thank you for the work put into making this great add-on, I'm currently running V1.0.10 and using alt+z to hide the UI. Upon doing so, all other add-ons are hidden with the exception of SimpleEnergyBar, which stays on the screen. I believe having the OPTION of having this hidden when the UI is would be a superlative improvement to this already fantastic add-on. I've included a screenshot for reference.

![Screenshot_SEB1UI](https://user-images.githubusercontent.com/23511326/65649443-935e4380-dfd4-11e9-9fa4-0e677932ef2f.png)

**Comment by Hoizame** [comment]
thanks fixed :)

**Comment by Glitchingreality** [comment]
Just tested it, working great, glad to see that it now hides properly when the UI is hidden. Good work! 👍
